Superpowered v2.6.7
superpoweredSDK/web-audio-javascript-webassembly-SDK-interactive-audio pull request #43
Opened 2024-04-19 16:54 UTC by dodds-cc

Release v2.6.7, with the following changes

1. Superpowered Advanced Audio Player:

- Song duration is returned as a float value
- Current pitch bend percent can be retrieved

2. Added Advanced Audio Player pitch bend example to the Javascript repository.

2024-04-20 07:15 UTC, gaborszanto commented on examples/example_pitchbend/main.js
> +    if (pitchShift < -12) pitchShift = -12; else if (pitchShift > 12) pitchShift = 12;
Can we have more "Javascript" here? Such as:

`pitchShift = Math.min(12, Math.max(-12, pitchShift + parseInt(e.target.value)));`

2024-04-20 07:17 UTC, gaborszanto commented on examples/example_pitchbend/main.js
> +    document.getElementById('pitch-shift-display').innerText = ' pitch shift: ' + ((pitchShift < 1) ? pitchShift : '+' + pitchShift) + ' ';
I think it's "textContent" these days, not "innerText".

2024-04-20 07:19 UTC, gaborszanto commented on examples/example_pitchbend/main.js
> +        faster,
Isn't this a bug? I think it's missing the key "faster".

Something like: `faster: value < 0 ? 0 : 1,`

2024-04-20 07:22 UTC, gaborszanto commented on examples/example_pitchbend/processor.js
> +            if (this.cancelledPitchBend) this.cancelledPitchBend = false;
Is the "if" necessary here? Just set it to false?

2024-04-20 07:23 UTC, gaborszanto requested changes
Please check my comments.

2024-04-22 12:19 UTC, dodds-cc commented on examples/example_pitchbend/assets/processor.js
> +        this.cancelledPitchBend = !this.cancelledPitchBend;
yes, I agree. Updated.

2024-04-22 13:29 UTC, dodds-cc commented
@gaborszanto Can you merge this now please?

2024-04-22 14:18 UTC, gaborszanto approved these changes

2024-04-22 14:18 UTC, merged